// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJzOfqUPiLxInf6Rz94VwTUZNbcJz_xMI',
    appId: '1:982167399947:web:f1879e0ffafdef8314610e',
    messagingSenderId: '982167399947',
    projectId: 'hari-open-source-project',
    authDomain: 'hari-open-source-project.firebaseapp.com',
    storageBucket: 'hari-open-source-project.firebasestorage.app',
    measurementId: 'G-1FN1JRSM56',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZH2K1BT0c4rntWz6qYvQn8QI7f8f-qQI',
    appId: '1:982167399947:android:4eaf145b825863a214610e',
    messagingSenderId: '982167399947',
    projectId: 'hari-open-source-project',
    storageBucket: 'hari-open-source-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEJGFgD8NtmkkSh-qtSRIEK1mH8iTl7zk',
    appId: '1:982167399947:ios:985c94597bc15d2414610e',
    messagingSenderId: '982167399947',
    projectId: 'hari-open-source-project',
    storageBucket: 'hari-open-source-project.firebasestorage.app',
    iosBundleId: 'com.example.openpro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEJGFgD8NtmkkSh-qtSRIEK1mH8iTl7zk',
    appId: '1:982167399947:ios:985c94597bc15d2414610e',
    messagingSenderId: '982167399947',
    projectId: 'hari-open-source-project',
    storageBucket: 'hari-open-source-project.firebasestorage.app',
    iosBundleId: 'com.example.openpro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJzOfqUPiLxInf6Rz94VwTUZNbcJz_xMI',
    appId: '1:982167399947:web:232e02199fc4189514610e',
    messagingSenderId: '982167399947',
    projectId: 'hari-open-source-project',
    authDomain: 'hari-open-source-project.firebaseapp.com',
    storageBucket: 'hari-open-source-project.firebasestorage.app',
    measurementId: 'G-BM9V6450PF',
  );
}
